# Generated by Django 4.2.6 on 2023-11-03 18:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KhachSan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenkhachsan', models.CharField(max_length=200, null=True)),
                ('diachi', models.CharField(max_length=200, null=True)),
                ('sdt', models.CharField(max_length=200, null=True)),
                ('mota', models.CharField(max_length=200, null=True)),
                ('email_ks', models.CharField(max_length=200, null=True)),
                ('anhkhachsan', models.ImageField(blank=True, null=True, upload_to='')),
                ('ngay_them', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='LoaiPhong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenloaiphong', models.CharField(max_length=200, null=True)),
                ('mota_loaiphong', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Phong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loaigiuong', models.CharField(max_length=200, null=True)),
                ('mota', models.CharField(max_length=200, null=True)),
                ('dientich', models.CharField(max_length=200, null=True)),
                ('phongtam', models.CharField(max_length=200, null=True)),
                ('soluongnguoi', models.IntegerField()),
                ('giaphong', models.FloatField()),
                ('trangthaiphong', models.CharField(max_length=200, null=True)),
                ('khachsan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.khachsan')),
                ('loaiphong', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.loaiphong')),
            ],
        ),
        migrations.CreateModel(
            name='TienNghi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='')),
                ('tentiennghi', models.CharField(max_length=200, null=True)),
                ('mota_tiennghi', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tinh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tentinh', models.CharField(max_length=200, null=True)),
                ('anhtinh', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='SapXepTN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngaytrangbi', models.DateTimeField(auto_now_add=True)),
                ('phong', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.phong')),
                ('tiennghi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.tiennghi')),
            ],
        ),
        migrations.AddField(
            model_name='khachsan',
            name='tinh',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.tinh'),
        ),
        migrations.CreateModel(
            name='HoaDon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trangthaihoanthanh', models.CharField(max_length=200, null=True)),
                ('ngay_gio_dat', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Danhgia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diem', models.IntegerField()),
                ('binhluan', models.CharField(max_length=200, null=True)),
                ('ngay_danhgia', models.DateTimeField(auto_now_add=True)),
                ('phong', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.phong')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ChiTietHoaDon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngay_gio_nhan', models.DateTimeField()),
                ('ngay_gio_tra', models.DateTimeField()),
                ('soluong', models.IntegerField()),
                ('dongia', models.FloatField()),
                ('hoadon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.hoadon')),
                ('phong', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.phong')),
            ],
        ),
        migrations.CreateModel(
            name='Anh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anhphong', models.ImageField(blank=True, null=True, upload_to='')),
                ('phong', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.phong')),
            ],
        ),
    ]
