# Generated by Django 4.2.6 on 2023-11-21 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_khachsan_loaiphong_phong_tiennghi_tinh_sapxeptn_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='khachsan',
            name='ngay_them',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
