# Generated by Django 4.2.6 on 2023-11-24 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_danhgia_phong_danhgia_hoadon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='danhgia',
            name='user',
        ),
        migrations.AddField(
            model_name='danhgia',
            name='khachsan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.khachsan'),
        ),
    ]
