# Generated by Django 4.2.6 on 2023-11-24 09:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_danhgia_user_danhgia_khachsan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='danhgia',
            name='hoadon',
        ),
        migrations.RemoveField(
            model_name='danhgia',
            name='khachsan',
        ),
        migrations.AddField(
            model_name='danhgia',
            name='phong',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.phong'),
        ),
        migrations.AddField(
            model_name='danhgia',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
